server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fornewsapp
    username: postgres
    password: '0001'
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

